# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14.15.4

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run jshint
          - npm run test-with-coverage
          - npx snyk auth $SNYK_TOKEN
          - npx snyk test
          - npm test
  branches:
    master:
      - step:
          script:
            - npm install
            - npm run jshint
            - npm run test-with-coverage
            - npx snyk auth $SNYK_TOKEN
            - npx snyk test
            - ./deploy.sh
